services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
#    command: tail -f /dev/null
    command: ["poetry", "run", "python", "main.py"]

